// Static mock dataset so `npm run dev` renders the dashboard with no backend.
// Shapes mirror the backend JobRead JSON. Salary bands here are pre-filled to
// represent what the LLM/heuristic estimator would have produced.

import type { Job } from "../types";

export const mockJobs: Job[] = [
  {
    id: 1,
    source: "seed",
    external_id: "seed-001",
    title: "Senior Backend Engineer",
    company: "Northwind Labs",
    location: "San Francisco, CA",
    remote: false,
    description:
      "Own and scale our payments API in Python/FastAPI. Tune Postgres, run infrastructure on AWS.",
    url: "https://example.com/jobs/seed-001",
    stack: ["Python", "FastAPI", "PostgreSQL", "AWS"],
    salary_min: 175000,
    salary_max: 210000,
    salary_currency: "USD",
    salary_period: "year",
    salary_source: "posting",
    salary_confidence: null,
    salary_rationale: "",
    posted_at: "2026-05-02T09:00:00",
    collected_at: "2026-05-15T00:00:00",
    enriched_at: null,
  },
  {
    id: 2,
    source: "seed",
    external_id: "seed-002",
    title: "Frontend Engineer (React)",
    company: "Brightwave",
    location: "Remote (US)",
    remote: true,
    description:
      "Build delightful dashboards with React 18, TypeScript and Tailwind. Strong eye for glassmorphism UI.",
    url: "https://example.com/jobs/seed-002",
    stack: ["TypeScript", "React", "Vite", "Tailwind"],
    salary_min: 132000,
    salary_max: 168000,
    salary_currency: "USD",
    salary_period: "year",
    salary_source: "anthropic",
    salary_confidence: 0.82,
    salary_rationale:
      "Senior-leaning remote React role; estimate from stack and US remote market.",
    posted_at: "2026-05-10T12:30:00",
    collected_at: "2026-05-15T00:00:00",
    enriched_at: "2026-05-15T00:05:00",
  },
  {
    id: 3,
    source: "seed",
    external_id: "seed-003",
    title: "Machine Learning Engineer",
    company: "Quanta AI",
    location: "New York, NY",
    remote: false,
    description:
      "Train and serve recommendation models at scale with PyTorch and Kubernetes-based serving.",
    url: "https://example.com/jobs/seed-003",
    stack: ["Python", "PyTorch", "Machine Learning", "Kubernetes"],
    salary_min: 182000,
    salary_max: 232000,
    salary_currency: "USD",
    salary_period: "year",
    salary_source: "anthropic",
    salary_confidence: 0.78,
    salary_rationale: "ML role in NYC with strong infra requirements.",
    posted_at: "2026-04-28T08:15:00",
    collected_at: "2026-05-15T00:00:00",
    enriched_at: "2026-05-15T00:05:00",
  },
  {
    id: 4,
    source: "seed",
    external_id: "seed-004",
    title: "Junior Full-Stack Developer",
    company: "Tinkertown",
    location: "Austin, TX",
    remote: false,
    description: "Entry-level role across a Node.js/React stack with mentorship.",
    url: "https://example.com/jobs/seed-004",
    stack: ["JavaScript", "Node.js", "React", "SQL"],
    salary_min: 80000,
    salary_max: 95000,
    salary_currency: "USD",
    salary_period: "year",
    salary_source: "posting",
    salary_confidence: null,
    salary_rationale: "",
    posted_at: "2026-05-14T10:00:00",
    collected_at: "2026-05-15T00:00:00",
    enriched_at: null,
  },
  {
    id: 5,
    source: "seed",
    external_id: "seed-005",
    title: "Staff Site Reliability Engineer",
    company: "Cloudpeak",
    location: "Remote (Global)",
    remote: true,
    description:
      "Lead reliability for a multi-region platform with deep Kubernetes, Terraform, and Go.",
    url: "https://example.com/jobs/seed-005",
    stack: ["Go", "Kubernetes", "Terraform", "AWS"],
    salary_min: 198000,
    salary_max: 252000,
    salary_currency: "USD",
    salary_period: "year",
    salary_source: "heuristic",
    salary_confidence: 0.35,
    salary_rationale:
      "Heuristic estimate from stack, seniority, and location signals (no LLM provider configured).",
    posted_at: "2026-05-01T16:45:00",
    collected_at: "2026-05-15T00:00:00",
    enriched_at: "2026-05-15T00:05:00",
  },
  {
    id: 6,
    source: "seed",
    external_id: "seed-007",
    title: "Senior Rust Engineer",
    company: "Ferrous Systems Co",
    location: "Berlin, DE",
    remote: true,
    description:
      "Build high-performance networking components in async Rust. Systems programming experience.",
    url: "https://example.com/jobs/seed-007",
    stack: ["Rust", "WebAssembly", "gRPC"],
    salary_min: 137000,
    salary_max: 174000,
    salary_currency: "USD",
    salary_period: "year",
    salary_source: "anthropic",
    salary_confidence: 0.74,
    salary_rationale: "Senior Rust role; Berlin remote-friendly market.",
    posted_at: "2026-05-06T13:00:00",
    collected_at: "2026-05-15T00:00:00",
    enriched_at: "2026-05-15T00:05:00",
  },
  {
    id: 7,
    source: "seed",
    external_id: "seed-014",
    title: "Senior Frontend Engineer",
    company: "Northwind Labs",
    location: "Seattle, WA",
    remote: false,
    description:
      "Lead the frontend for our analytics suite with React/Next.js and a shared design system.",
    url: "https://example.com/jobs/seed-014",
    stack: ["TypeScript", "React", "Next.js", "Tailwind"],
    salary_min: 160000,
    salary_max: 195000,
    salary_currency: "USD",
    salary_period: "year",
    salary_source: "posting",
    salary_confidence: null,
    salary_rationale: "",
    posted_at: "2026-05-11T09:25:00",
    collected_at: "2026-05-15T00:00:00",
    enriched_at: null,
  },
  {
    id: 8,
    source: "seed",
    external_id: "seed-015",
    title: "Backend Engineer (Node.js)",
    company: "Brightwave",
    location: "Remote (US)",
    remote: true,
    description: "Build GraphQL APIs in TypeScript/Node with ownership over reliability.",
    url: "https://example.com/jobs/seed-015",
    stack: ["TypeScript", "Node.js", "PostgreSQL", "GraphQL"],
    salary_min: 128000,
    salary_max: 162000,
    salary_currency: "USD",
    salary_period: "year",
    salary_source: "gemini",
    salary_confidence: 0.69,
    salary_rationale: "Mid-to-senior Node role; US remote market.",
    posted_at: "2026-05-13T11:50:00",
    collected_at: "2026-05-15T00:00:00",
    enriched_at: "2026-05-15T00:05:00",
  },
];
